// HTML:
// CREARE UN DIV CON UN ID SPECIFICO PER CONTENERE TUTTE LE CARTE
// CREARE LE CARTE, OGNUNA CON UN DIV CON UNA CLASSE SPECIFICA E CHE ABBIA ALTRI DIV FRONTE/RETRO (NASCOSTI?)

// JS:
// GENERARE LE CARTE IN BASE AL NUMERO DI COPPIE DESIDERATE
// ASSEGNARE IMG O SIMBOLI A CIASCUNA CARTA (USARE UN ARRAY PER GESTIRE LE COPPIE)
// MESCOLARE LE CARTE CASUALMENTE

// LOGICA DEL GIOCO:
// QUANDO UNA CARTA VIENE CLICCATA, RIVELA IL SUO CONTENUTO
// SE DUE CARTE SONO UGUALI, SUCCEDE QCS. SE SONO DIVERSE, VERRANNO COPERTE DI NUOVO
// IL GIOCO TERMINA QUANDO TUTTE LE COPPIE VENGONO TROVATE

// CSS:
// CREARE IL FRONTE E IL RETRO DELLE CARTE
// RESPONSIVE SUGLI ALTRI SCHERMI
//
